[build]
  base = "/"
  publish = "dist"
  command = "npm run build"
  functions = "built_functions/"
  functionsSource = "functions/"

[dev]
  base = "dist/"
  publish = ""
  command = "npm start"
  port = 3000
  framework = "create-react-app"